AttendanceManagementProject/Controllers/AttendanceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AttendanceManagementProject.Models;

namespace AttendanceManagementProject.Controllers
{
    public class AttendanceController : Controller
    {
        private dbAttendanceEntity db = new dbAttendanceEntity();

        // GET: Attendance
        public ActionResult Index()
        {
            //var attendances = db.Attendances.Include(a => a.Class).Include(a => a.Student);


            int teacherId = ((Teacher)Session["Teacher"]).id;
            var getClasses = db.Classes.Where(c => c.teacher_id == teacherId);

            List<Attendance> attendances = new List<Attendance>();

            foreach (Class C in getClasses)
            {
                var stu = db.Attendances.Where(s => s.class_id == C.id);
                foreach (var myStu in stu)
                {
                    attendances.Add(myStu);
                }
            }


            return View(attendances.ToList());
        }

        // GET: Attendance/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendance attendance = db.Attendances.Find(id);
            if (attendance == null)
            {
                return HttpNotFound();
            }
            return View(attendance);
        }

        // GET: Attendance/Create
        public ActionResult Create()
        {

            int teacherId = ((Teacher)Session["Teacher"]).id;
            ViewBag.class_id = new SelectList(db.Classes.Where(c => c.teacher_id == teacherId), "id", "school_name");

            List<Student> students = new List<Student>();

            foreach (Class C in db.Classes.Where(c => c.teacher_id == teacherId))
            {
                var stu = db.Students.Where(s => s.class_id == C.id);
                foreach (var myStu in stu)
                {
                    students.Add(myStu);
                }
            }

            ViewBag.student_id = new SelectList(students, "id", "name");
            return View();
        }

        // POST: Attendance/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "class_id,student_id,date,status")] Attendance attendance)
        {
            if (ModelState.IsValid)
            {
                db.Attendances.Add(attendance);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.class_id = new SelectList(db.Classes, "id", "school_name", attendance.class_id);
            ViewBag.student_id = new SelectList(db.Students, "id", "name", attendance.student_id);
            return View(attendance);
        }

        // GET: Attendance/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendance attendance = db.Attendances.Find(id);
            if (attendance == null)
            {
                return HttpNotFound();
            }
            ViewBag.class_id = new SelectList(db.Classes, "id", "school_name", attendance.class_id);
            ViewBag.student_id = new SelectList(db.Students, "id", "name", attendance.student_id);
            return View(attendance);
        }

        // POST: Attendance/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "class_id,student_id,date,status")] Attendance attendance)
        {
            if (ModelState.IsValid)
            {
                db.Entry(attendance).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.class_id = new SelectList(db.Classes, "id", "school_name", attendance.class_id);
            ViewBag.student_id = new SelectList(db.Students, "id", "name", attendance.student_id);
            return View(attendance);
        }

        // GET: Attendance/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendance attendance = db.Attendances.Find(id);
            if (attendance == null)
            {
                return HttpNotFound();
            }
            return View(attendance);
        }

        // POST: Attendance/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Attendance attendance = db.Attendances.Find(id);
            db.Attendances.Remove(attendance);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AttendanceManagementProject/Controllers/LoginController.cs
using AttendanceManagementProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AttendanceManagementProject.Controllers
{
    public class LoginController : Controller
    {

        private dbAttendanceEntity db = new dbAttendanceEntity();

        // GET: Login
        public ActionResult Index()
        {
            Session["Teacher"] = null;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "email,password")] Teacher teacher)
        {

            Teacher teach = null;
            foreach (Teacher t in db.Teachers) {
                if (t.email.Equals(teacher.email) && t.password.Equals(teacher.password)) {
                    teach = t;
                    break;
                }
            }

            if (teach==null) {
                ModelState.AddModelError("Error", "Check Email and Password Again");
            }

            if (ModelState.IsValid)
            {
                Session["Teacher"] = teach;
                return RedirectToAction("Create","Class");
            }

            return View(teacher);
        }
    }
}

AttendanceManagementProject/Views/Shared/LeftSideBar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LeftSideBar</title>
</head>
<body>
    <div class="row profile">
        <div class="col-md-3">
            <div class="profile-sidebar">
                <!-- SIDEBAR USERPIC -->
                <div class="profile-userpic">
                    <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
                </div>
                <!-- END SIDEBAR USERPIC -->
                <!-- SIDEBAR USER TITLE -->
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name">
                        Name: @(((AttendanceManagementProject.Models.Teacher)Session["Teacher"]).name)
                    </div>
                    <div class="profile-usertitle-name">
                        Gender: @(((AttendanceManagementProject.Models.Teacher)Session["Teacher"]).gender)
                    </div>
                    <div class="profile-usertitle-name">
                        Phone: @(((AttendanceManagementProject.Models.Teacher)Session["Teacher"]).phone)
                    </div>
                </div>

                <!-- END SIDEBAR BUTTONS -->
                <!-- SIDEBAR MENU -->
                <div class="profile-usermenu">
                    <ul class="nav">
                        @{

                            <li class="active">
                                @Html.ActionLink("Create", "Create")
                            </li>
                                    <li>
                                        @Html.ActionLink("Edit", "Edit")
                                    </li>
                                    <li>
                                        @Html.ActionLink("View", "View")
                                    </li>
                                    <li>
                                        @Html.ActionLink("Delete", "Delete")
                                    </li>
                        }
                    </ul>
                </div>
                <!-- END MENU -->
            </div>
        </div>
        <div class="col-md-9">
            <div class="profile-content">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

AttendanceManagementProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/LeftSideBar.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Session["Teacher"] != null)
                {
                    @Html.ActionLink("SAMS ", "Index", "Attendance", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.Label("SAMS", new { @class = "navbar-brand" })
                    
                }
            </div>
            @if (Session["Teacher"] != null)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Class", "Index", "Class")</li>
                        <li>@Html.ActionLink("Student", "Index", "Student")</li>
                        <li>@Html.ActionLink("Attendace", "Index", "Attendance")</li>
                        <li>@Html.ActionLink("Setting", "Edit", "Teacher", new { id = (((AttendanceManagementProject.Models.Teacher)Session["Teacher"]).id) }, null)</li>
                        <li>@Html.ActionLink("Logout", "Index", "Login")</li>
                    </ul>
                </div>
            }
            
        </div>
    </div>

    <div class="container body-content">

                    @RenderBody()


        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MSAS</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>